// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SHI_NOTE.Models
{
    public partial class ShiDocuments
    {
        public int KeyNo { get; set; }
        public string DocumentName { get; set; }
        public int? UsersKeyno { get; set; }

        public virtual ShiUsers UsersKeynoNavigation { get; set; }
    }
}