// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SHI_NOTE.Models
{
    public partial class ShiUsers
    {
        public ShiUsers()
        {
            ShiDocuments = new HashSet<ShiDocuments>();
        }

        /// <summary>
        /// 自增主键用户编号
        /// </summary>
        public int KeyNo { get; set; }
        /// <summary>
        /// 系统账号：自动生成不可修改
        /// </summary>
        public string Account { get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
        public string UserEmail { get; set; }
        /// <summary>
        /// 昵称
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// 0代表男，1代表女，2代表私密（默认为私密）
        /// </summary>
        public int UserSex { get; set; }
        /// <summary>
        /// 头像
        /// </summary>
        public string UserImg { get; set; }
        /// <summary>
        /// 个人签名
        /// </summary>
        public string UserSign { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        public string UserPwd { get; set; }
        public string UserToken { get; set; }
        /// <summary>
        /// token到期时间
        /// </summary>
        public DateTime? TokenEndtiem { get; set; }

        public virtual ICollection<ShiDocuments> ShiDocuments { get; set; }
    }
}